# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('interior', models.CharField(choices=[('AP', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440 \u043a\u0432\u0430\u0440\u0442\u0438\u0440'), ('HO', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440 \u0434\u043e\u043c\u0430, \u043a\u043e\u0442\u0435\u0434\u0436\u0430'), ('RE', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440\u044b \u0440\u0435\u0441\u0442\u043e\u0440\u0430\u043d\u043e\u0432, \u043a\u0430\u0444\u0435, \u0431\u0430\u0440\u043e\u0432'), ('OF', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440\u044b \u043e\u0444\u0438\u0441\u043e\u0432, \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432'), ('HOT', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440 \u043e\u0442\u0435\u043b\u044f')], default='AP', max_length=1)),
                ('img', models.ImageField(upload_to=b'')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=29)),
                ('descript', models.CharField(max_length=350)),
                ('img', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
