# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntogru_kernel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '\u0440\u0430\u0431\u043e\u0442\u0443', 'verbose_name_plural': '\u041d\u0430\u0448\u0438 \u0440\u0430\u0431\u043e\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': '\u043e\u0442\u0437\u044b\u0432', 'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': '\u0443\u0441\u043b\u0443\u0433\u0443', 'verbose_name_plural': '\u0423\u0441\u043b\u0443\u0433\u0438'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='text',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='interior',
            field=models.CharField(choices=[('AP', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440 \u043a\u0432\u0430\u0440\u0442\u0438\u0440'), ('HO', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440 \u0434\u043e\u043c\u0430, \u043a\u043e\u0442\u0435\u0434\u0436\u0430'), ('RE', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440\u044b \u0440\u0435\u0441\u0442\u043e\u0440\u0430\u043d\u043e\u0432, \u043a\u0430\u0444\u0435, \u0431\u0430\u0440\u043e\u0432'), ('OF', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440\u044b \u043e\u0444\u0438\u0441\u043e\u0432, \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u0432'), ('HOT', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440 \u043e\u0442\u0435\u043b\u044f')], default='AP', max_length=3, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='avatar',
            field=models.ImageField(upload_to=b'', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='services',
            name='descript',
            field=models.CharField(max_length=350, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=29, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
