# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntogru_kernel', '0003_howwework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howwework',
            name='text',
        ),
        migrations.AddField(
            model_name='howwework',
            name='descript',
            field=models.CharField(default='', max_length=350, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='howwework',
            name='title',
            field=models.CharField(default='', max_length=29, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
    ]
