# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntogru_kernel', '0004_auto_20170608_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=17, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('address', models.CharField(max_length=500, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441 \u043e\u0444\u0438\u0441\u0430')),
                ('email', models.EmailField(max_length=254, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u044b')),
                ('vk_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0433\u0440\u0443\u043f\u043f\u0443 VK')),
                ('instagram_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Instagram')),
                ('twitter_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Twitter')),
                ('fb_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0433\u0440\u0443\u043f\u043f\u0443 Facebook')),
                ('about_descript', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('year_of_foundation', models.IntegerField(verbose_name='\u0413\u043e\u0434 \u043e\u0441\u043d\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('designers', models.IntegerField(verbose_name='\u0414\u0438\u0437\u0430\u0439\u043d\u0435\u0440\u043e\u0432 \u0432 \u043a\u043e\u043c\u0430\u043d\u0434\u0435')),
                ('contractors', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u043e\u0441\u0442\u043e\u044f\u043d\u043d\u044b\u0445 \u043f\u043e\u0434\u0440\u044f\u0434\u0447\u0438\u043a\u043e\u0432')),
                ('active', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043f\u0440\u043e\u0444\u0438\u043b\u044f')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0444\u0438\u043b\u044c',
                'verbose_name_plural': '\u041e\u0441\u043d\u043e\u0432\u043d\u044b\u0435 \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
            },
        ),
    ]
