# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntogru_kernel', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='number',
            field=models.CharField(max_length=35, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
    ]
