# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-23 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntogru_kernel', '0006_auto_20170823_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='alt_number',
            field=models.CharField(default=1, max_length=17, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='number',
            field=models.CharField(max_length=17, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
    ]
