# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import puntogru_kernel.models


class Migration(migrations.Migration):

    dependencies = [
        ('puntogru_kernel', '0007_auto_20170823_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=puntogru_kernel.models.get_file_path, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u043f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntogru_kernel.Portfolio', verbose_name='\u041f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044e',
            },
        ),
    ]
